MAIN/urls.py
from django.urls import path

from .views import *

app_name = 'user'
urlpatterns = [
    path('register/', register_form, name='register'),
    path('logout/', logoutView, name='logout'),
    path('login/', loginView, name='login'),
    path('dashboard/<uuid:uuid>/', dashboardView, name='dashboard'),
]

POLLS/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('accounts/', include('MAIN.urls')),
]

MAIN/models.py
import uuid

from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

# Create your models here.

class UserManager(BaseUserManager):
    def create_user(self, username, password, email='123@gmail.com' ,is_active=True, is_admin=False, is_staff=False):
        if not username:
            raise ValueError('users must have an username')
        if not email:
            raise ValueError('users must have an email')
        if not password:
            raise ValueError('users must have a password')
        user_obj = self.model(
            email=self.normalize_email(email)
        )
        user_obj.username = username
        user_obj.set_password(password)
        user_obj.save(using=self._db)
        return user_obj

    def create_staffuser(self, username, password=None):
        user = self.create_user(
            username, 
            password=password,
            is_staff=True
        )

    def create_superuser(self, username, password=None):
        user = self.create_user(
            username, 
            password=password,
            is_admin=True,
            is_staff=True
        )

class User(AbstractBaseUser):
    username = models.CharField(max_length=255, unique=True, default='')
    email = models.EmailField(blank=True, null=True)
    uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    hak_pilih = models.IntegerField(default=1, editable=False)
    active = models.BooleanField(default=True)
    staff = models.BooleanField(default=True)
    admin = models.BooleanField(default=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=True):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.staff
    
    @property
    def is_admin(self):
        return self.admin
    
    @property
    def is_active(self):
        return self.active

class Calon(models.Model):
    objects = UserManager()

    username = models.CharField(max_length=255)
    email = models.EmailField()
    password = models.CharField(max_length=255)
    suara = models.IntegerField(default=0, editable=False)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False)

    def __str__(self):
        return self.username

MAIN/forms.py
from django import forms

class RegisterForm(forms.Form):
	username = forms.CharField(max_length=255)
	email = forms.EmailField()
	password = forms.CharField(max_length=255, widget=forms.PasswordInput)
	token = forms.CharField(max_length=10)

class LoginForm(forms.Form):
	username = forms.CharField(max_length=255)
	password = forms.CharField(max_length=255, widget=forms.PasswordInput)

MAIN/views.py
from django.shortcuts import render, redirect
from .models import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from .forms import *

#Create your views here.

def user_exist(request):
    context = {
        'pageTitle':'REGISTER',
    }
    return render(request, 'main/user_exist.html', context)

def wrong_token(request):
    context = {
        'pageTitle':'REGISTER',
    }
    return render(request, 'main/wrong_token.html', context)

def null_hak_pilih(request, uuid):
    user = User.objects.get(uuid=uuid)
    context = {
        'user':user,
        'pageTitle':'PILIH',
    }
    return render(request, 'main/null_hak_pilih.html', context)

def register_form(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            token = form.cleaned_data.get('token')

            a = Calon.objects.all()

            for i in a:
                if username == i.username or email == i.email:
                    return user_exist(request)

            if token != "12345":
                return wrong_token(request)

            new_user = Calon(username=username, email=email, password=password)
            new_user.save()
            return redirect('/')
    else:
        form = RegisterForm()
    
    context = {
        'form':form,
    }

    return render(request, 'main/register.html', context)

def loginView(request):
    form = LoginForm()
    condition = False
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data.get('username'), password=form.cleaned_data.get('password'))
            if user:
                condition = False
                login(request, user)
                return redirect('/accounts/dashboard/'+str(user.uuid))
            else:
                condition = True
    else:
        form = LoginForm()

    context = {
        'form':form,
        'pageTitle':'LOGIN',
        'condition':condition,
    }

    return render(request, 'main/login.html', context)


def logoutView(request):
    logout(request)
    return redirect('/accounts/logout')

@login_required
def dashboardView(request, uuid):
    user = User.objects.get(uuid=uuid)
    list_calon = Calon.objects.all()
    context = {
        'user':user,
        'calon':list_calon,
    }
    return render(request, 'main/dashboard.html', context)

POLLS/views.py
from django.shortcuts import render, redirect

def home(request):
	context = {
		'pageTitle':'HOME',
	}
	return render(request, 'index.html', context)

MAIN/templates/main/dashboard.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

	<h1>dashbiard {{user.username}}</h1><br>

	<ul>
	{% for i in calon %}
		<li>{{i.username}} || {{i.suara}} suara</li>
		<a href=""><button type="button">pilih</button></a>
		<button type="button">detail</button><br><br>
	{% endfor %}
	</ul>

	<a href="{% url 'user:logout' %}">keluar</a>

{% endblock content %}

MAIN/templates/main/login.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
	<link rel="stylesheet" type="text/css" href="{% static 'style/user/login.css' %}">
{% endblock style %}

{% block content %}

	<div class="card">
		<form method="POST">
			{% csrf_token %}

			<div class="login">
			{% for i in form %}

				<p>{{i.label}}</p>
				<p>{{i}}</p>

			{% endfor %}

			<button type="submit" name='Login'>login</button>
			</div>
		</form>

		<a href="{% url 'home' %}"><button class="btn btn-danger" type="button">back</button></a>
	</div>

	{% if condition %}
		<script type="text/javascript">
			alert("username atau password anda salah");
			document.location.href = "{% url 'user:login' %}"
		</script>
	{% endif %}

{% endblock content %}

MAIN/templates/main/null_hak_pilih.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

	<script type="text/javascript">
		alert("anda sudah memilih");
		document.location.href = "{% url 'user:dashboard' user.uuid %}";
	</script>

{% endblock content %}

MAIN/templates/main/register.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
	<link rel="stylesheet" type="text/css" href="{% static 'style/user/register.css' %}">
{% endblock style %}

{% block content %}

	<div class="card">
		<form method="POST">
			{% csrf_token %}
			<div class="register">
				{% for i in form %}
					<p>{{i.label}}</p>
					<p>{{i}}<br></p>
				{% endfor %}
				<button type="submit">daftar</button>
			</div>

			<div class="specific-button">
				<a href="{% url 'home' %}"><button class="btn btn-danger" type="button">back</button></a>
			</div>
		</form>
	</div>

{% endblock content %}

MAIN/templates/main/user_exist.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	
	<script type="text/javascript">
		alert("username atau email telah terdaftar sebagai calon");
		document.location.href = "{% url 'user:register' %}";
	</script>

{% endblock content %}

MAIN/templates/main/wrong_token.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

	<script type="text/javascript">
		alert("token yang anda masukkan salah");
		document.location.href = "{% url 'user:register' %}";
	</script>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{{pageTitle}}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}">
	{% block style %}{% endblock style %}
</head>
<body>

	{% block content %}{% endblock content %}


	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
	<link rel="stylesheet" type="text/css" href="{% static 'style/home.css' %}">
{% endblock style %}

{% block content %}


    <h1>SELAMAT DATANG</h1>
    <p>ini adalah form pemilihan</p>


	<div class="card">
		<div class="choices">
			<h3>POLLS</h3>
			<a href="{% url 'user:login' %}"><button class="btn btn-success" type="button">memilih</button></a>
			<a href="{% url 'user:register' %}"><button class="btn btn-success" type="button">mencalon</button></a>
		</div>
	</div>


{% endblock content %}